### ISSUE TITLE
Can't right click in game

### ISSUE THREAD

**Issue by Ainjeel** [FluffierThanThou/Fluffy_Breakdowns#1]
When i used this mod i couldn't right click on anything on the map. I also used only this mod activated, and it seems to have this issue even without other mods.

Best regards
Angiel from Ludeon

**Comment by FluffierThanThou** [comment]
Hey Ainjeel, thats odd. Could you please attach your output-log.txt in a game where this happens? It's probably creating some errors that would help me figure this out.
